### ISSUE TITLE
How to set up grafana and jaeger

### ISSUE THREAD

**Issue by mabushey** [banzaicloud/istio-operator#118]
While I despise Helm, installing istio with grafana is as simple as adding `--set grafana.enabled=true  --set grafana.security.enabled=true` to the `helm template` command. Jaeger integration is simply `--set tracing.enabled=true`. I believe the policy on the istio operator is not to support directly these addons, however, I would love some kind of docs to add Prometheus/Grafana, Jaeger, and Knative to Istio brought up via the operator.

Does it make sense to just copy out all elements from istio.yaml (generated by `helm template`) that have to do with each and apply them?

**Comment by martonsereg** [comment]
This is definitely on our short-term roadmap to integrate easily with Prometheus, Grafana and Jaeger.
But we believe that it should not be the responsibility of this operator to manage them, but, instead, to provide easy ways to integrate with external deployments/operators.
If it's not a demo/PoC scenario, developers often already have their own way of managing these components - like the Prometheus operator configured with other rules and targets.

As a first step it would be great to have some docs about the recommended way of installing these components. If you're willing to contribute a doc like that, we'd appreciate it. Copying them out of the Helm chart should work, but it shouldn't really matter how you set those up.

*Jaeger*
Integration with Jaeger involves configuring the address of the Jaeger service in Istio's configmap. Currently it's hardcoded in the operator (`zipkin.istio-system:9411`), but it means that if you set this service up in the `istio-system` namespace, it should automatically start working. I've tested it with the Jaeger dev setup (https://github.com/jaegertracing/jaeger-kubernetes#development-setup), it sets up that service properly.

*Grafana*
Integration with Grafana basically means adding the default dashboards that are available on [grafana.com](https://grafana.com/orgs/istio/dashboards). You can set up Grafana using the Istio Helm chart, the [stable](https://github.com/helm/charts/tree/master/stable/grafana) Helm chart, or simply with `kubectl`, the important part is to add the dashboards.

*Prometheus*
Istio's Helm chart of Prometheus does nothing more than installing a simple Prometheus deployment and pre-configuring a few Istio specific targets. If you have Prometheus running somehow (using the Prometheus operator, a Helm chart, or `helm template` and `kubectl`), you'll need to add the Istio specific targets from [here](https://github.com/istio/istio/blob/release-1.0/install/kubernetes/helm/istio/charts/prometheus/templates/configmap.yaml#L17:L322) to get the metrics.

*Knative*
We haven't tried it yet, so I can't add anything useful to that, but again if you do a PoC and want to contribute some docs about it, it'd be great!

**Comment by mabushey** [comment]
The `jaeger-all-in-one-template.yml` seems pretty worthless, it creates it's own ELB. As I'm running Istio I already have an ELB from ingress. I pulled this config out of the old istio.yaml file I used before the operator, and it works. I removed all reference to the tiller crap. The Istio operator logs to it, and the UI is available by routing to `jaeger-query.istio-system.svc.cluster.local`

```
---
# Source: istio/charts/tracing/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: istio-tracing
  namespace: istio-system
  labels:
    app: istio-tracing
    chart: tracing-1.0.6
    release: istio
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jaeger
      annotations:
        sidecar.istio.io/inject: "false"
        scheduler.alpha.kubernetes.io/critical-pod: ""
    spec:
      containers:
        - name: jaeger
          image: "docker.io/jaegertracing/all-in-one:1.5"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9411
            - containerPort: 16686
            - containerPort: 5775
              protocol: UDP
            - containerPort: 6831
              protocol: UDP
            - containerPort: 6832
              protocol: UDP
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: COLLECTOR_ZIPKIN_HTTP_PORT
            value: "9411"
          - name: MEMORY_MAX_TRACES
            value: "50000"
          livenessProbe:
            httpGet:
              path: /
              port: 16686
          readinessProbe:
            httpGet:
              path: /
              port: 16686
          resources:
            requests:
              cpu: 10m

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 2
            preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
          - weight: 2
            preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - ppc64le
          - weight: 2
            preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - s390x

---
# Source: istio/charts/tracing/templates/service-jaeger.yaml

apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: jaeger-query
    namespace: istio-system
    annotations:
    labels:
      app: jaeger
      jaeger-infra: jaeger-service
      chart: tracing-1.0.6
      release: istio
  spec:
    ports:
      - name: query-http
        port: 16686
        protocol: TCP
        targetPort: 16686
    selector:
      app: jaeger
- apiVersion: v1
  kind: Service
  metadata:
    name: jaeger-collector
    namespace: istio-system
    labels:
      app: jaeger
      jaeger-infra: collector-service
      chart: tracing-1.0.6
      release: istio
  spec:
    ports:
    - name: jaeger-collector-tchannel
      port: 14267
      protocol: TCP
      targetPort: 14267
    - name: jaeger-collector-http
      port: 14268
      targetPort: 14268
      protocol: TCP
    selector:
      app: jaeger
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    name: jaeger-agent
    namespace: istio-system
    labels:
      app: jaeger
      jaeger-infra: agent-service
      chart: tracing-1.0.6
      release: istio
  spec:
    ports:
    - name: agent-zipkin-thrift
      port: 5775
      protocol: UDP
      targetPort: 5775
    - name: agent-compact
      port: 6831
      protocol: UDP
      targetPort: 6831
    - name: agent-binary
      port: 6832
      protocol: UDP
      targetPort: 6832
    clusterIP: None
    selector:
      app: jaeger



---
# Source: istio/charts/tracing/templates/service.yaml
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: zipkin
    namespace: istio-system
    labels:
      app: jaeger
      chart: tracing-1.0.6
      release: istio
  spec:
    type: ClusterIP
    ports:
      - port: 9411
        targetPort: 9411
        protocol: TCP
        name: http
    selector:
      app: jaeger
- apiVersion: v1
  kind: Service
  metadata:
    name: tracing
    namespace: istio-system
    annotations:
    labels:
      app: jaeger
      chart: tracing-1.0.6
      release: istio
  spec:
    ports:
      - name: http-query
        port: 80
        protocol: TCP
        targetPort: 16686
    selector:
      app: jaeger
---
```
