### ISSUE TITLE
Support resource configuration

### ISSUE THREAD

**Issue by orbatschow** [banzaicloud/istio-operator#151]
**Is your feature request related to a problem? Please describe.**
As some people like me are running only a few microservices it would be great to have a way to customize the resource utilization (especially for the pilot chart).

**Describe the solution you'd like to see**
It could look exactly like the Helm chart:
```
pilot:
    enabled: true
    image: "docker.io/istio/pilot:1.1.1"
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
    minReplicas: 1
    maxReplicas: 5
```
