### ISSUE TITLE
Allow modification of sidecarinjector configmap

### ISSUE THREAD

**Issue by dad264** [banzaicloud/istio-operator#172]
**Is your feature request related to a problem? Please describe.**
We use Istio setup in a way our our pod should _only_ opt-in for the sidecar. Following the table [here](https://istio.io/help/ops/setup/injection), we would need to set the sidecar default policy to `disabled` in order to get the behavior we seek. Unfortunately, it seems that the istio-operator (and thus the Kind: Istio) doesn't allow the override of that parameter. 

This assumption is based on my novice reading of the code near https://github.com/banzaicloud/istio-operator/blob/62e4141ca0848ba02049ad2b61d7996956bf0a19/pkg/resources/sidecarinjector/configmap.go#L42 

**Describe the solution you'd like to see**
Allow modification of the sidecarinjector policy.

Possibly:
```
  sidecarInjector:
    enabled: true
    image: "docker.io/istio/sidecar_injector:1.1.2"
    replicaCount: 1
    rewriteAppHTTPProbe: true
    policy: disabled
```

**Describe alternatives you've considered**
I've edited the configmap by hand right now, but suspect that the istio-operator will overwrite that at some point. 

**Additional context**
None
