### ISSUE TITLE
Setting loadBalancerIP on ingress

### ISSUE THREAD

**Issue by xeor** [banzaicloud/istio-operator#194]
**Is your feature request related to a problem? Please describe.**
It looks like there is no way currently to set `loadBalancerIP` on the ingress gateway..

**Describe the solution you'd like to see**
A way to set `loadBalancerIP` in the yaml under `gateways.ingress.loadBalancerIp`

**Describe alternatives you've considered**
Setting the ip as:

```
   gateways:
     ingress:
       serviceAnnotations:
         loadBalancerIP: 10.1.2.3
```
but that does nothing.. :)
