### ISSUE TITLE
Missing ClusterRole rule required by citadel

### ISSUE THREAD

**Issue by mousavian** [banzaicloud/istio-operator#235]
**Describe the bug**
Hey guys,
As part of installation, manager tries to provision a clusterRole for citadel component which [requires](https://github.com/banzaicloud/istio-operator/blob/6ecac42a97a1b52b8d0a149c9f810d8e587eea99/pkg/resources/citadel/rbac.go#L51-L55) `create` access on `tokenreviews` but manager's clusterRole does not have that permission itself; hence throwing an error:
```json
{
"level":"error",
"ts":1560482910.994635,
"logger":"kubebuilder.controller",
"msg":"Reconciler error",
"controller":"config-controller",
"request":"istio-system/v1",
"error":"could not reconcile istio: failed to reconcile resource: creating resource failed: clusterroles.rbac.authorization.k8s.io \"istio-citadel-cluster-role\" is forbidden: attempt to grant extra privileges: [{[create] [authentication.k8s.io] [tokenreviews] [] []}] user=&{system:serviceaccount:istio-system:default c57f4a81-8d96-11e9-a113-0a5c456c8770
..."
}
```
This can be the result of [having this rule](https://github.com/banzaicloud/istio-operator/blob/70dc2704e3c15b58fb42bde8fb024f888893199d/config/overlays/auth-proxy-enabled/rbac/auth_proxy_role.yaml#L5-L9) in `auth_proxy_role.yaml` overlay instead of base.

**Steps to reproduce the issue:**
```yaml
# kustomization.yaml
namespace: istio-system

bases:
   - github.com/banzaicloud/istio-operator/config?ref=release-1.1
   - github.com/banzaicloud/istio-operator/config/base?ref=release-1.1
   - github.com/banzaicloud/istio-operator/config/overlays/basic?ref=release-1.1
```

```
kubectl apply -k .
```
**Expected behavior**
Installation with no error

**Screenshots**
N/A

**Additional context**
N/A
