### ISSUE TITLE
istio-sidecar-injector error with release-1.2

### ISSUE THREAD

**Issue by ppennanen** [banzaicloud/istio-operator#259]
**Describe the bug**

Istio-sidecar-injector does not appear to work with istio-operator `release-1.2`. Pods are not created in namespaces with `istio-injection=enabled`. `kubectl describe rs` for a failed deployment gives the error: 

```
Events:
  Type     Reason        Age                 From                   Message
  ----     ------        ----                ----                   -------
  Warning  FailedCreate  12m (x20 over 50m)  replicaset-controller  Error creating: Internal error occurred: admission webhook "sidecar-injector.istio.io" denied the request: template: inject:28:92: executing "inject" at <ne .Values.global.pr...>: error calling ne: invalid type for comparison
``` 

istio-sidcar-injector logs:

```
2019-07-12T07:19:12.408953Z	info	Invalid template: template: inject:28:92: executing "inject" at <ne .Values.global.pr...>: error calling ne: invalid type for comparison rewriteAppHTTPProbe: {{ valueOrDefault .Values.sidecarInjectorWebhook.rewriteAppHTTPProbe false }}
{{- if .Values.global.podDNSSearchNamespaces }}
dnsConfig:
  searches:
    {{- range .Values.global.podDNSSearchNamespaces }}
    - {{ render . }}
    {{- end }}
{{- end }}
initContainers:
{{ if ne (annotation .ObjectMeta `sidecar.istio.io/interceptionMode` .ProxyConfig.InterceptionMode) "NONE" }}
- name: istio-init
  image: "{{ .Values.global.proxy_init.image }}"
  args:
  - "-p"
  - "15001"
  - "-u"
  - 1337
  - "-m"
  - "{{ annotation .ObjectMeta `sidecar.istio.io/interceptionMode` .ProxyConfig.InterceptionMode }}"
  - "-i"
  - "{{ annotation .ObjectMeta `traffic.sidecar.istio.io/includeOutboundIPRanges` .Values.global.proxy.includeIPRanges }}"
  - "-x"
  - "{{ annotation .ObjectMeta `traffic.sidecar.istio.io/excludeOutboundIPRanges` .Values.global.proxy.excludeIPRanges }}"
  - "-b"
  - "{{ annotation .ObjectMeta `traffic.sidecar.istio.io/includeInboundPorts` (includeInboundPorts .Spec.Containers) }}"
  - "-d"
  - "{{ excludeInboundPort (annotation .ObjectMeta `status.sidecar.istio.io/port` .Values.global.proxy.statusPort) (annotation .ObjectMeta `traffic.sidecar.istio.io/excludeInboundPorts` .Values.global.proxy.excludeInboundPorts) }}"
  {{ if or (isset .ObjectMeta.Annotations `traffic.sidecar.istio.io/excludeOutboundPorts`) (ne .Values.global.proxy.excludeOutboundPorts "") -}}
  - "-o"
  - "{{ annotation .ObjectMeta `traffic.sidecar.istio.io/excludeOutboundPorts` .Values.global.proxy.excludeOutboundPorts }}"
  {{ end -}}
  {{ if (isset .ObjectMeta.Annotations `traffic.sidecar.istio.io/kubevirtInterfaces`) -}}
  - "-k"
  - "{{ index .ObjectMeta.Annotations `traffic.sidecar.istio.io/kubevirtInterfaces` }}"
  {{ end -}}
  imagePullPolicy: "{{ .Values.global.imagePullPolicy }}"
  resources:
    limits:
      cpu: 100m
      memory: 50Mi
    requests:
      cpu: 10m
      memory: 10Mi
  
  securityContext:
    runAsUser: 0
    runAsNonRoot: false
    capabilities:
      add:
      - NET_ADMIN
    {{- if .Values.global.proxy.privileged }}
    privileged: true
    {{- end }}
  restartPolicy: Always
  env:
  {{- if contains "*" (annotation .ObjectMeta `traffic.sidecar.istio.io/includeInboundPorts` "") }}
  - name: INBOUND_CAPTURE_PORT
    value: 15006
  {{- end }}
  
{{ end -}}

containers:
- name: istio-proxy
  image: "{{ annotation .ObjectMeta `sidecar.istio.io/proxyImage` .Values.global.proxy.image }}"
  ports:
  - containerPort: 15090
    protocol: TCP
    name: http-envoy-prom
  args:
  - proxy
  - sidecar
  - --domain
  - $(POD_NAMESPACE).svc.{{ .Values.global.proxy.clusterDomain }}
  - --configPath
  - "{{ .ProxyConfig.ConfigPath }}"
  - --binaryPath
  - "{{ .ProxyConfig.BinaryPath }}"
  - --serviceCluster
  {{ if ne "" (index .ObjectMeta.Labels `app`) -}}
  - "{{ index .ObjectMeta.Labels "app" }}.$(POD_NAMESPACE)"
  {{ else -}}
  - "{{ valueOrDefault .DeploymentMeta.Name `istio-proxy` }}.{{ valueOrDefault .DeploymentMeta.Namespace `default` }}"
  {{ end -}}
  - --drainDuration
  - "{{ formatDuration .ProxyConfig.DrainDuration }}"
  - --parentShutdownDuration
  - "{{ formatDuration .ProxyConfig.ParentShutdownDuration }}"
  - --discoveryAddress
  - "{{ annotation .ObjectMeta `sidecar.istio.io/discoveryAddress` .ProxyConfig.DiscoveryAddress }}"

{{- if .Values.global.proxy.logLevel }}
  - --proxyLogLevel={{ .Values.global.proxy.logLevel }}
{{- end}}
{{- if .Values.global.proxy.componentLogLevel }}
  - --proxyComponentLogLevel={{ .Values.global.proxy.componentLogLevel }}
{{- end}}
  - --dnsRefreshRate
  - {{ .Values.global.proxy.dnsRefreshRate }}
  - --connectTimeout
  - "{{ formatDuration .ProxyConfig.ConnectTimeout }}"
  {{- if .Values.global.proxy.envoyStatsd.enabled }}
  - --statsdUdpAddress
  - "{{ .ProxyConfig.StatsdUdpAddress }}"
{{- end }}
{{- if .Values.global.proxy.envoyMetricsService.enabled }}
  - --envoyMetricsServiceAddress
  - "{{ .ProxyConfig.EnvoyMetricsServiceAddress }}"
{{- end }}
  - --proxyAdminPort
  - "{{ .ProxyConfig.ProxyAdminPort }}"
  {{ if gt .ProxyConfig.Concurrency 0 -}}
  - --concurrency
  - "{{ .ProxyConfig.Concurrency }}"
  {{ end -}}
  - --controlPlaneAuthPolicy
  - "{{ annotation .ObjectMeta `sidecar.istio.io/controlPlaneAuthPolicy` .ProxyConfig.ControlPlaneAuthPolicy }}"
{{- if (ne (annotation .ObjectMeta "status.sidecar.istio.io/port" .Values.global.proxy.statusPort) "0") }}
  - --statusPort
  - "{{ annotation .ObjectMeta `status.sidecar.istio.io/port` .Values.global.proxy.statusPort }}"
  - --applicationPorts
  - "{{ annotation .ObjectMeta `readiness.status.sidecar.istio.io/applicationPorts` (applicationPorts .Spec.Containers) }}"
{{- end }}
{{- if .Values.global.trustDomain }}
  - --trust-domain={{ .Values.global.trustDomain }}
{{- end }}
  env:
  - name: POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  - name: POD_NAMESPACE
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace
  - name: INSTANCE_IP
    valueFrom:
      fieldRef:
        fieldPath: status.podIP
{{ if eq .Values.global.proxy.tracer "datadog" }}
  - name: HOST_IP
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP
{{ end }}
  - name: ISTIO_META_POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  - name: ISTIO_META_CONFIG_NAMESPACE
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace
  - name: ISTIO_META_INTERCEPTION_MODE
    value: "{{ or (index .ObjectMeta.Annotations `sidecar.istio.io/interceptionMode`) .ProxyConfig.InterceptionMode.String }}"
  - name: ISTIO_META_INCLUDE_INBOUND_PORTS
    value: "{{ annotation .ObjectMeta `traffic.sidecar.istio.io/includeInboundPorts` (applicationPorts .Spec.Containers) }}"
  {{- if .Values.global.network }}
  - name: ISTIO_META_NETWORK
    value: "{{ .Values.global.network }}"
  {{- end }}
  {{ if .ObjectMeta.Annotations }}
  - name: ISTIO_METAJSON_ANNOTATIONS
    value: |
           {{ toJSON .ObjectMeta.Annotations }}
  {{ end }}
  {{ if .ObjectMeta.Labels }}
  - name: ISTIO_METAJSON_LABELS
    value: |
           {{ toJSON .ObjectMeta.Labels }}
  {{ end }}
  {{- if (isset .ObjectMeta.Annotations `sidecar.istio.io/bootstrapOverride`) }}
  - name: ISTIO_BOOTSTRAP_OVERRIDE
    value: "/etc/istio/custom-bootstrap/custom_bootstrap.json"
  {{- end }}
  {{- if .Values.global.sds.customTokenDirectory }}
  - name: ISTIO_META_SDS_TOKEN_PATH
    value: "{{ .Values.global.sds.customTokenDirectory -}}/sdstoken"
  {{- end }}
  imagePullPolicy: {{ .Values.global.imagePullPolicy }}
  {{ if ne (annotation .ObjectMeta `status.sidecar.istio.io/port` .Values.global.proxy.statusPort) `0` }}
  readinessProbe:
    httpGet:
      path: /healthz/ready
      port: {{ annotation .ObjectMeta `status.sidecar.istio.io/port` .Values.global.proxy.statusPort }}
    initialDelaySeconds: {{ annotation .ObjectMeta `readiness.status.sidecar.istio.io/initialDelaySeconds` .Values.global.proxy.readinessInitialDelaySeconds }}
    periodSeconds: {{ annotation .ObjectMeta `readiness.status.sidecar.istio.io/periodSeconds` .Values.global.proxy.readinessPeriodSeconds }}
    failureThreshold: {{ annotation .ObjectMeta `readiness.status.sidecar.istio.io/failureThreshold` .Values.global.proxy.readinessFailureThreshold }}
  {{ end -}}
  securityContext:
    {{- if .Values.global.proxy.privileged }}
    privileged: true
    {{- end }}
    {{- if ne .Values.global.proxy.enableCoreDump true }}
    readOnlyRootFilesystem: true
    {{- end }}
    {{ if eq (annotation .ObjectMeta `sidecar.istio.io/interceptionMode` .ProxyConfig.InterceptionMode) `TPROXY` -}}
    capabilities:
      add:
      - NET_ADMIN
    runAsGroup: 1337
    {{ else -}}
    {{ if and .Values.global.sds.enabled .Values.global.sds.useTrustworthyJwt }}
    runAsGroup: 1337
    {{- end }}
    runAsUser: 1337
    {{- end }}
  resources:
  {{ if or (isset .ObjectMeta.Annotations `sidecar.istio.io/proxyCPU`) (isset .ObjectMeta.Annotations `sidecar.istio.io/proxyMemory`) -}}
    requests:
      {{ if (isset .ObjectMeta.Annotations `sidecar.istio.io/proxyCPU`) -}}
      cpu: "{{ index .ObjectMeta.Annotations `sidecar.istio.io/proxyCPU` }}"
      {{ end}}
      {{ if (isset .ObjectMeta.Annotations `sidecar.istio.io/proxyMemory`) -}}
      memory: "{{ index .ObjectMeta.Annotations `sidecar.istio.io/proxyMemory` }}"
      {{ end }}
  {{ else -}}
{{- if .Values.global.proxy.resources }}
    {{ toYaml .Values.global.proxy.resources | indent 4 }}
{{- end }}
  {{  end -}}
  volumeMounts:
  {{ if (isset .ObjectMeta.Annotations `sidecar.istio.io/bootstrapOverride`) }}
  - mountPath: /etc/istio/custom-bootstrap
    name: custom-bootstrap-volume
  {{- end }}
  - mountPath: /etc/istio/proxy
    name: istio-envoy
  {{- if .Values.global.sds.enabled }}
  - mountPath: /var/run/sds
    name: sds-uds-path
    readOnly: true
  {{- if .Values.global.sds.useTrustworthyJwt }}
  - mountPath: /var/run/secrets/tokens
    name: istio-token
  {{- end }}
  {{- if .Values.global.sds.customTokenDirectory }}
  - mountPath: "{{ .Values.global.sds.customTokenDirectory -}}"
    name: custom-sds-token
    readOnly: true
  {{- end }}
  {{- else }}
  - mountPath: /etc/certs/
    name: istio-certs
    readOnly: true
  {{- end }}
  {{- if and (eq .Values.global.proxy.tracer "lightstep") .Values.global.tracer.lightstep.cacertPath }}
  - mountPath: {{ directory .ProxyConfig.GetTracing.GetLightstep.GetCacertPath }}
    name: lightstep-certs
    readOnly: true
  {{- end }}
    {{- if isset .ObjectMeta.Annotations `sidecar.istio.io/userVolumeMount` }}
    {{ range $index, $value := fromJSON (index .ObjectMeta.Annotations `sidecar.istio.io/userVolumeMount`) }}
  - name: "{{  $index }}"
    {{ toYaml $value | indent 4 }}
    {{ end }}
    {{- end }}
volumes:
{{- if (isset .ObjectMeta.Annotations `sidecar.istio.io/bootstrapOverride`) }}
- name: custom-bootstrap-volume
  configMap:
    name: {{ annotation .ObjectMeta `sidecar.istio.io/bootstrapOverride` "" }}
{{- end }}
- emptyDir:
    medium: Memory
  name: istio-envoy
{{- if .Values.global.sds.enabled }}
- name: sds-uds-path
  hostPath:
    path: /var/run/sds
{{- if .Values.global.sds.customTokenDirectory }}
- name: custom-sds-token
  secret:
    secretName: sdstokensecret
{{- end }}
{{- if .Values.global.sds.useTrustworthyJwt }}
- name: istio-token
  projected:
    sources:
    - serviceAccountToken:
        path: istio-token
        expirationSeconds: 43200
        audience: {{ .Values.global.trustDomain }}
{{- end }}
{{- else }}
- name: istio-certs
  secret:
    optional: true
    {{ if eq .Spec.ServiceAccountName "" }}
    secretName: istio.default
    {{ else -}}
    secretName: {{  printf "istio.%s" .Spec.ServiceAccountName }}
    {{  end -}}
  {{- if isset .ObjectMeta.Annotations `sidecar.istio.io/userVolume` }}
  {{range $index, $value := fromJSON (index .ObjectMeta.Annotations `sidecar.istio.io/userVolume`) }}
- name: "{{ $index }}"
  {{ toYaml $value | indent 2 }}
  {{ end }}
  {{ end }}
{{- end }}
{{- if and (eq .Values.global.proxy.tracer "lightstep") .Values.global.tracer.lightstep.cacertPath }}
- name: lightstep-certs
  secret:
    optional: true
    secretName: lightstep.cacert
{{- end }}


2019-07-12T07:19:12.408997Z	info	Injection data: err=template: inject:28:92: executing "inject" at <ne .Values.global.pr...>: error calling ne: invalid type for comparison spec=
```

This looks related to https://github.com/istio/istio/issues/15288

**Steps to reproduce the issue:**

1. Install istio-operator `release-1.2` in a (GKE) Kubernetes cluster
2. Create an istio resource
3. Create a deployment in a namespace with Istio sidecar injection enabled.

**Expected behavior**

Istio-proxy sidecars should be injected in pods.

**Additional context**

istio-operator `release-1.2`, istio version `1.2.2`

**Comment by waynz0r** [comment]
Hi @ppennanen,

I could not reproduce this issue on a fresh GKE cluster.

Could you please paste the Istio CR that you applied?

**Comment by ppennanen** [comment]
So this is the Istio CR used. It fails to work on a fresh GKE cluster. The setup also uses a pre-existing root cert, but the errors don't seem related to that.

```
apiVersion: istio.banzaicloud.io/v1beta1
kind: Istio
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: istio
  namespace: istio-system
spec:
  version: "1.2.2"
  useMCP: true
  mtls: true
  multiMesh: true
  includeIPRanges: "*"
  excludeIPRanges: ""
  autoInjectionNamespaces:
  - "default"
  controlPlaneSecurityEnabled: false
  istioCoreDNS:
    enabled: true
    replicaCount: 1
  defaultResources:
    requests:
      cpu: 10m
  sds:
    enabled: true
    udsPath: "unix:/var/run/sds/uds_path"
    useTrustworthyJwt: false
    useNormalJwt: true
  pilot:
    enabled: true
    image: "docker.io/istio/pilot:1.2.2"
    replicaCount: 1
    minReplicas: 1
    maxReplicas: 5
    traceSampling: 1.0
    resources:
      requests:
        cpu: 500m
        memory: 2048Mi
  citadel:
    enabled: true
    image: "docker.io/istio/citadel:1.2.2"
    caSecretName: "cacerts"
  galley:
    enabled: true
    image: "docker.io/istio/galley:1.2.2"
    replicaCount: 1
  gateways:
    enabled: true
    ingress:
      enabled: true
      replicaCount: 1
      minReplicas: 1
      maxReplicas: 5
      serviceType: "LoadBalancer"
      loadBalancerIP: ""
      serviceAnnotations: {}
      serviceLabels: {}
      ports:
        - port: 15020
          targetPort: 15020
          name: status-port
        - port: 80
          targetPort: 80
          name: http2
          nodePort: 31380
        - port: 443
          name: https
          nodePort: 31390
        - port: 15443
          targetPort: 15443
          name: tls
      sds:
        enabled: true
        image: "docker.io/istio/node-agent-k8s:1.2.2"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 2000m
            memory: 1024Mi
      applicationPorts: ""
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 2000m
          memory: 1024Mi
    egress:
      enabled: true
      replicaCount: 1
      minReplicas: 1
      maxReplicas: 5
      serviceType: "ClusterIP"
      serviceAnnotations: {}
      serviceLabels: {}
      ports:
        - port: 80
          name: http2
        - port: 443
          name: https
        - port: 15443
          targetPort: 15443
          name: tls
      applicationPorts: ""
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 2000m
          memory: 256Mi
    k8singress:
      enabled: false
  mixer:
    enabled: true
    image: "docker.io/istio/mixer:1.2.2"
    replicaCount: 1
    minReplicas: 1
    maxReplicas: 5
  sidecarInjector:
    enabled: true
    image: "docker.io/istio/sidecar_injector:1.2.2"
    replicaCount: 1
    rewriteAppHTTPProbe: true
    autoInjectionPolicyEnabled: true
    init:
      resources:
        requests:
          cpu: 10m
          memory: 10Mi
        limits:
          cpu: 100m
          memory: 50Mi
  nodeAgent:
    enabled: true
    image: "docker.io/istio/node-agent-k8s:1.2.2"
  proxy:
    image: "docker.io/istio/proxyv2:1.2.2"
    enableCoreDump: false
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 2000m
        memory: 1024Mi
  proxyInit:
    image: "docker.io/istio/proxy_init:1.2.2"
  defaultPodDisruptionBudget:
    enabled: true
  outboundTrafficPolicy:
    mode: ALLOW_ANY
  tracing:
    enabled: false

```
