### ISSUE TITLE
Beta channel for charts?

### ISSUE THREAD

**Issue by xeor** [banzaicloud/istio-operator#263]
**Is your feature request related to a problem? Please describe.**

I want istio `1.2`, but to get that I need the `realese-1.2` of the operator. The chart published at kubernetes-charts.banzaicloud.com only contains the `0.0.14` chart, not the needed `0.2.0`.

**Describe the solution you'd like to see**

Publish charts faster (if this is stable?). https://github.com/banzaicloud/istio-operator/releases sais `0.2.0` was released 8 days ago, but there are still the old chart in the chart-museum published.

**Describe alternatives you've considered**

Doing manuall install, and following the docs in the default-branch (`release-1.2`). However, the helm install mentioned still doesnt work..

**Additional context**

Validation of installing an istio resource fails with `spec.version in body should match '^1.1'`.

Not sure if I should have submitted this as a bug or feature-request

**Comment by sagikazarmark** [comment]
@xeor thanks for opening this issue. Beta channel is indeed a good idea, but I think it's not necessary in this case.

While it might be a bit confusing, the chart is versioned independently from the operator. On the linked releases page you can find chart tags prefixed with `chart/`.

It's probably easier to follow chart versions on the Helm Hub page: https://hub.helm.sh/charts/banzaicloud-stable/istio-operator

This shows that the latest chart version is `0.0.14` and at the time of the release the latest operator version was `0.1.21`.

You can try installing `0.2.0` operator by simply setting the `operator.image.tag` helm value (which is also documented on the page linked above). Feel free to open a bug ticket if you experience any issues.

**Comment by xeor** [comment]
Thanks for the reply.. Thats what I thought, but then this doesn't make much sense :)

Note that I use helm v3 alpha, but that shouldn't have anything to say...

I installed using `h3 upgrade -i istio-operator banzaicloud-stable/istio-operator --set-string operator.image.tag=0.2.0`, and I verify it's config is as it should (`h3 status -o yaml istio-operator`):

```
config:
  affinity: {}
  fullnameOverride: ""
  nameOverride: ""
  nodeSelector: {}
  operator:
    image:
      pullPolicy: IfNotPresent
      repository: banzaicloud/istio-operator
      tag: 0.2.0
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
  prometheusMetrics:
    authProxy:
      enabled: true
      image:
        pullPolicy: IfNotPresent
        repository: gcr.io/kubebuilder/kube-rbac-proxy
        tag: v0.4.0
    enabled: true
  rbac:
    enabled: true
    psp:
      enabled: false
  tolerations: []
```

Then I try to install a simple `Istio`:

```
apiVersion: istio.banzaicloud.io/v1beta1
kind: Istio
metadata:
  name: istio
spec:
  version: "1.2.2"
  mtls: true
```

but it gives the error

```
The Istio "istio" is invalid: []: Invalid value: map[string]interface {}{"apiVersion":"istio.banzaicloud.io/v1beta1", "kind":"Istio", "metadata":map[string]interface {}{"annotations":map[string]interface {}{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"istio.banzaicloud.io/v1beta1\",\"kind\":\"Istio\",\"metadata\":{\"annotations\":{},\"name\":\"istio\",\"namespace\":\"istio-system\"},\"spec\":{\"mtls\":true,\"version\":\"1.2.2\"}}\n"}, "creationTimestamp":"2019-07-21T18:45:39Z", "generation":1, "name":"istio", "namespace":"istio-system", "uid":"bc5ddcb5-abe7-11e9-9f37-b8aeed7edbbd"}, "spec":map[string]interface {}{"mtls":true, "version":"1.2.2"}}: validation failure list:
spec.version in body should match '^1.1'
```
