### ISSUE TITLE
Support multiple ingress gateways

### ISSUE THREAD

**Issue by Laci21** [banzaicloud/istio-operator#271]
**Problem statement:**
The current version of the operator has the Istio ingress gateway configuration in the main `Istio` custom resource. It means that only one ingress gateway can be configured and reconciled through the operator, but it is a common use-case to have multiple ingress gateways in an environment.

**Possible workaround:**
Configure the Istio control plane (and one ingress gateway) through the operator and manage the rest of the gateways manually by installing them with Helm, or a simple `kubectl apply`.

**Solution:**
Decouple the ingress gateway configuration from the rest of the control plane components by creating a new custom resource definition (`IstioIngressGateway`) that holds these properties, and a new controller in the operator that manages this component. Adding a new CR would create a new gateway, deleting the CR would delete that gateway.
The current APIs and controllers are generated by [Kubebuilder v1](https://book-v1.book.kubebuilder.io), the new CRDs and controllers should use the same version.

Make sure that the current Istio control plane CRD remains backward compatible, so an ingress gateway could still be created through the main CR.

**Comment by blaketastic2** [comment]
@Laci21 Do you think this really requires a new CRD? Could we not just do something like this?

```yaml
apiVersion: istio.banzaicloud.io/v1beta1
kind: Istio
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: istio-operator
  namespace: istio-system
spec:
  version: "1.2.5"
  gateways:
    enabled: true
    ingress:
      enabled: true
      serviceType: "LoadBalancer"
      ....
    ingress-2:
      enabled: true
      serviceType: "LoadBalancer"
      ....
    ingress-3:
      enabled: true
      serviceType: "LoadBalancer"
     ....
    egress:
      enabled: false
    k8sIngress:
      enabled: false
```

```go
// GatewaysConfiguration defines config options for Gateways
type GatewaysConfiguration struct {
	Enabled             *bool                           `json:"enabled,omitempty"`
	IngressConfig       GatewayConfiguration            `json:"ingress,omitempty"`
	EgressConfig        GatewayConfiguration            `json:"egress,omitempty"`
	K8sIngress          K8sIngressConfiguration         `json:"k8singress,omitempty"`
	OtherIngressConfigs map[string]GatewayConfiguration `json:"-"`
}

// MarshalJSON is the implementation of the interface in encoding/json/Marshaler
func (g GatewaysConfiguration) MarshalJSON() ([]byte, error) {

	type GatewaysConfiguration_ GatewaysConfiguration // prevent recursion
	b, _ := json.Marshal(GatewaysConfiguration_(g))

	var m map[string]json.RawMessage
	_ = json.Unmarshal(b, &m)

	// Add tags to the map, possibly overriding struct fields
	for k, v := range g.OtherIngressConfigs {
		b, _ = json.Marshal(v)
		m[k] = b
	}

	return json.Marshal(m)
}
```

I'd love some feedback on this approach. If you think it will work, I can work toward a PR over the next couple of days
