### ISSUE TITLE
Cannot use Kustomize to change the name from istio-sample to istio

### ISSUE THREAD

**Issue by mabushey** [banzaicloud/istio-operator#334]
**Describe the bug**
Kustomize is awesome, the Bonzai operator is awesome, but I have no clue what the Bonzai Kustomize docs are even getting at. The operator is deployed via a make deploy and nothing needs to be tweeked so there is minimal need for kustomize. On the doc page `bases:` is used. This is deprecated and should be `resources:`

Once the operator is installed then I want to apply patches to the  `istio-operator/config/samples/istio_v1beta1_istio.yaml` to set the zipkin address, annotations on the gateway, InjectionNamespaces, etc. These are fine, but I cannot figure out how to change the annoying `istio-sample` name to `istio`. Here's what I have:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
resources:
  - istio-operator/config/samples/istio_v1beta1_istio.yaml
patchesJson6902:
- target:
    version: istio.banzaicloud.io/v1beta1
    kind: Istio
    name: istio-sample
  path: istio-name-patch.yaml
#patchesStrategicMerge:
#  - istio-tracing-patch.yaml
```

cat istio-name-patch.yaml
```
- op: replace
  path: /metadata/name
  value: istio
```
I've successfully used this same patch on namespaces, but somehow the `version: istio.banzaicloud.io/v1beta1` or `kind: Istio` is not matching.

**Steps to reproduce the issue:**
`✗  kustomize build .`                 
`Error: no matches for OriginalId ~G_istio.banzaicloud.io/v1beta1_Istio|~X|istio-sample; no matches for CurrentId ~G_istio.banzaicloud.io/v1beta1_Istio|~X|istio-sample; failed to find unique target for patch ~G_istio.banzaicloud.io/v1beta1_Istio|istio-sample`

**Expected behavior**
The name changes from `istio-sample` to `istio`

**Additional context**
release-1.4 branch

**Comment by Laci21** [comment]
Hi @mabushey,

Glad you like the operator!

First of all, we use the `Kubebuilder v1` operator framework which uses `Kustomize` for make deploy, that's why it's there and we use `Kustomize 2.X` that's why `bases:` is used instead of `resources:`.

AFAIK, the names of Kubernetes resources cannot be updated so I think it won't work like that. What you can do is delete the resource and then create it again with the new name.

About editing CR fields like zipkin address, annotations, etc., I think it's much easier to create your own `custom_istio_cr.yaml` file based on the `istio-operator/config/samples/istio_v1beta1_istio.yaml` file, but containing your changes and then simply doing a `kubectl -n=istio-system apply -f custom_istio_cr.yaml`. Wouldn't that be sufficient for your use case?

If you have further questions, I would recommend you to join our [Slack channel](https://slack.banzaicloud.io/) and we can continue the discussion on our [istio-operator channel](https://community-banzaicloud.slack.com/archives/CGKQF5HUP).

*Small nit: it's `Banzai`, not `Bonzai` :)*

**Comment by mabushey** [comment]
Banzai. :)

I wasn't very clear. From https://github.com/kubernetes-sigs/kustomize/blob/master/docs/v2.1.0.md#resources-expanded-bases-deprecated : `The bases field is now deprecated, and will be deleted in some future major release.`

 `Wouldn't that be sufficient for your use case?`
Absolutely not. Modifying `istio_v1beta1_istio.yaml` is the poster child for Kustomize, I can't think of a better example. I'm not going to manually merge in the SSL ARN info, zipkin address, autoinjection namespaces, etc every week when a new version of Istio comes out. I created patches and can apply them automatically with Kustomize.

I'm able to use that same patch file with a target on a namespace to change the name of the namespace back after a kustomize prefix, so you're at least partly wrong about updating the name of a resource. Are you saying this is a bug in Kustomize that I can't update the meta`/metadata/name` on a target of `version: istio.banzaicloud.io/v1beta`?

This works:
```
patchesJson6902:
- target:
    version: v1
    kind: Namespace
    name: logs
  path: namespace-patch.yaml
```
```
- op: replace
  path: /metadata/name
  value: logs
```
This doesn't work:
```
patchesJson6902:
- target:
    version: istio.banzaicloud.io/v1beta
    kind: Istio
    name: istio-sample
  path: istio-name-patch.yaml
```
```
- op: replace
  path: /metadata/name
  value: istio
```

**Comment by Laci21** [comment]
Thanks for the additional info, I understand your use case a little more now!

Please give us some time to investigate this, I don't have a clear picture on why this does not work yet.

Until then just a guess: Don't you need to provide the `namespace: istio-system` field as well to the target when patching the Istio CR resource?

**Comment by mabushey** [comment]
Hi @Laci21 :) I tried adding `namespace: istio-system` to the target but that didn't affect anything. Thanks for looking into this.

**Comment by Laci21** [comment]
Yeah, I was afraid so, it was only a wild guess :)

Probably it will be next week when we can look into this in more detail.

**Comment by Laci21** [comment]
@mabushey, could you please join our [Slack channel](https://slack.banzaicloud.io/) and we can continue debugging on our [istio-operator channel](https://community-banzaicloud.slack.com/archives/CGKQF5HUP) more effectively.

**Comment by mabushey** [comment]
Got it:

```
patchesJson6902:
- target:
    group: istio.banzaicloud.io
    version: v1beta1
    kind: Istio
    name: istio-sample
    namespace: istio-system
  path: istio-name-patch.yaml
```
I was missing the group under target. If I can free up some time I'll write a blog article on using kustomize with the Banzai operator, as the operator is awesome but the existing Banzai kustomize docs are irrelevant and don't apply to someone using the operator to run Istio.
