### ISSUE TITLE
integration with Prometheus/Grafana/Jaeger

### ISSUE THREAD

**Issue by martonsereg** [banzaicloud/istio-operator#41]
the Helm chart can install all of these, but it's probably not the scope of the operator to manage these components, but we should figure out how to integrate them.

**Comment by chriscowley** [comment]
not one of the devs, but I believe for Jaeger you simply need to control the `defaultConfig.zipkinAddress` in the istio `configMap`.

Is this more of a documentation issue than an enhancement?

**Comment by waynz0r** [comment]
@chriscowley for using an existing Jaeger that would be probably enough, although we want to make it explicitly configurable in the custom resource describing Istio config.

**Comment by chriscowley** [comment]
@waynz0r certainly that would be a good MVP for tracing support.

For what its worth I just tried adding a service that matched the default value for `defaultConfig.zipkinAddress` in the operator that pointed to a Jaeger pod. Nothing :( no traces at all

Is there anyone at Banzai who has POCed something similar?

**Comment by waynz0r** [comment]
@chriscowley it should work, we are looking into it!

**Comment by waynz0r** [comment]
@chriscowley by our tests it generally works, but the default sampling rate is 1 out of every 100 requests. I created an issue to support changing this value (see #75).

Right now you can change it by editing the `pilot` deployment `discovery` container's `PILOT_TRACE_SAMPLING` env variable. Try change it to 100 for testing, you should see spans popping up in Jaeger.

**Comment by waynz0r** [comment]
@chriscowley we have just released v0.0.7 with the feature to allow sampling rate configuration in the CR.

Please let us know if you still have tracing problem!

**Comment by chriscowley** [comment]
@waynz0r 1 out of 100 seems a little light - certainly explains why I was seeing nothing from ~20 page refreshes of the bookinfo app.
 
I'll test it during the week.

**Comment by chriscowley** [comment]
Got bored and tested it anyway. The variable you added works perfectly, but there is still one piece of "glue" I needed to add. 

The Istio seems to be hardwired to send the tracing sample to `zipkin:16686`. The Jaeger operator creates a service called `<jaeger-name>-query` which includes port 16686. I had to add a service that replicated that service called `zipkin` (my jaeger instance is called "tracing":

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jaeger
    app.kubernetes.io/component: all-in-one
    app.kubernetes.io/instance: tracing
    app.kubernetes.io/managed-by: jaeger-operator
    app.kubernetes.io/name: tracing
    app.kubernetes.io/part-of: jaeger
  name: zipkin
  namespace: istio-system
spec:
  clusterIP: None
  ports:
  - name: zipkin
    port: 9411
    protocol: TCP
    targetPort: 9411
  - name: c-tchan-trft
    port: 14267
    protocol: TCP
    targetPort: 14267
  - name: c-binary-trft
    port: 14268
    protocol: TCP
    targetPort: 14268
  selector:
    app: jaeger
    app.kubernetes.io/component: all-in-one
    app.kubernetes.io/instance: tracing
    app.kubernetes.io/managed-by: jaeger-operator
    app.kubernetes.io/name: tracing
    app.kubernetes.io/part-of: jaeger
  sessionAffinity: None
  type: ClusterIP
```

In my Istio config I have got:

```
spec:
  ...
  enabledServices:
  - name: "zipkin"
    labelSelector: "app=jaeger"
  ...
```

which from some logic I cannot remember from Friday appeared logical to me (is that supposed to create a zipkin service as part of Istio that attaches to any pods with the label "app=jaeger"?) as I cannot remember where I found it.

**Comment by waynz0r** [comment]
@chriscowley thanks for the feedback!

The operator managed Istio components send tracing to `zipkin.istio-system:9411`, but creating that service is outside of the operator's scope right know.

The `enabledServices` variable is in the `RemoteIstio` spec and based on that the operator will create selectorless services at the remote side and keeps the endpoint IP of those services in sync with the IP of the actual running pods at the local side.

If you would be interested we can discuss this in more detail on our community slack (https://slack.banzaicloud.io #istio-operator)

**Comment by vhosakot** [comment]
I'm not able to install istio's prometheus and grafana. Is this ticket going to be implemented anytime soon? Can we install install istio's prometheus and grafana using banzaicloud/istio-operator?

I added the following section in the istio CR yaml https://github.com/banzaicloud/istio-operator/blob/release-1.1/config/samples/istio_v1beta1_istio.yaml under the `spec:` section and it did not work and istio's prometheus and grafana were not deployed after I installed the istio CR:

```
  prometheus:
    enabled: true
    hub: docker.io/prom
    tag: v2.7.1
  grafana:
    enabled: true
    image:
      repository: grafana/grafana
      tag: 6.0.0
```
