### ISSUE TITLE
Istio Operator Configuration of PDB and Pilot

### ISSUE THREAD

**Issue by rtselizondo** [banzaicloud/istio-operator#415]
**Describe the bug**
The Pod Disruption Budget configuration selector deployed for istio pilot seems not to match what is deployed for the pod specification of istio pilot. 

**Steps to reproduce the issue:**
Currently we have the following version deployed: 
istio = "1.4.5"
helm chart = "0.0.36"
operator = "0.4.9"

Mostly standard deployment with mesh gateways. 

Description of the Pod Disruption Budget configuration. Shows the expected selector is: 
`app=istio-pilot`
```
k describe pdb -n istio-system istio-pilot
Name:           istio-pilot
Namespace:      istio-system
Min available:  1
Selector:       app=istio-pilot,istio=pilot
Status:
    Allowed disruptions:  0
    Current:              0
    Desired:              1
    Total:                0
Events:
  Type    Reason  Age                    From               Message
  ----    ------  ----                   ----               -------
  Normal  NoPods  31s (x96621 over 33d)  controllermanager  No matching pods found
```

Actual deployed pod for pilot shows the selector as:
 `app:pilot`

```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/psp: eks.privileged
    scheduler.alpha.kubernetes.io/critical-pod: ""
    sidecar.istio.io/inject: "false"
  creationTimestamp: "2020-03-16T17:41:51Z"
  generateName: istio-pilot-c5cdcd887-
  labels:
    app: pilot
    istio: pilot
    pod-template-hash: c5cdcd887
  name: istio-pilot-c5cdcd887-bbms2
  namespace: istio-system
```

**Expected behavior**
Expected that the selector for the deployed pilot pods would match the selector in the pdb
