### ISSUE TITLE
Init container istio-init pausing during startup

### ISSUE THREAD

**Issue by audrey-brightloom** [banzaicloud/istio-operator#423]
**Describe the bug**
When deploying via Helm the `istio-init` container of the first pod to start will wait for 7 minutes before initialization. Once that container has completed the service along with the `istio-proxy` container will start 1 min later. 

Once the first pod has completely started, the rest of the pods in the replica set start and complete right away.  

**Steps to reproduce the issue:**
Deploying via Helm to any service within the mesh. Our charts haven't changed between upgrading from istio 1.4.2 to 1.5.2.

**Expected behavior**
Prior to Istio 1.5.x, pods would complete initialization within 15-20 seconds. 

**Additional context**
Istio version: `1.5.2`
Operator version: `0.5.5`
Helm chart version: `0.0.45`

Current operator settings:

```
apiVersion: istio.banzaicloud.io/v1beta1
kind: Istio
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: istio-settings
spec:
  version: "1.5.2"
  meshPolicy:
    mtlsMode: PERMISSIVE
  autoMtls: true
  includeIPRanges: "*"
  excludeIPRanges: ""
  autoInjectionNamespaces:
  - "default"
  controlPlaneSecurityEnabled: false
  mountMtlsCerts: false
  # priorityClassName: system-cluster-critical
  defaultResources:
    requests:
      cpu: 10m
  mixerlessTelemetry:
    enabled: false
  sds:
    enabled: false
  istiod:
    enabled: true
  pilot:
    enabled: true
    image: "docker.io/istio/pilot:1.5.2"
    replicaCount: 1
    minReplicas: 1
    maxReplicas: 5
    traceSampling: 1.0
    resources:
      requests:
        cpu: 500m
        memory: 2048Mi
    certProvider: "istiod"
  citadel:
    enabled: false
    image: "docker.io/istio/citadel:1.5.2"
  galley:
    enabled: false
    image: "docker.io/istio/galley:1.5.2"
    replicaCount: 1
    enableServiceDiscovery: false
    enableAnalysis: false
  gateways:
    enabled: true
    ingress:
      enabled: true
      replicaCount: 1
      minReplicas: 1
      maxReplicas: 2
      serviceType: "LoadBalancer"
      loadBalancerIP: ""
      serviceAnnotations:
        service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      serviceLabels: {}
      ports:
        - port: 15020
          targetPort: 15020
          name: status-port
        - port: 80
          targetPort: 80
          name: http2
        - port: 443
          targetPort: 443
          name: https
        - port: 15443
          targetPort: 15443
          name: tls
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 2000m
          memory: 1024Mi
    egress:
      enabled: true
      replicaCount: 1
      minReplicas: 1
      maxReplicas: 1
      serviceType: "ClusterIP"
      serviceAnnotations: {}
      serviceLabels: {}
      ports:
        - port: 80
          targetPort: 80
          name: http2
        - port: 443
          targetPort: 443
          name: https
        - port: 15443
          targetPort: 15443
          name: tls
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 2000m
          memory: 256Mi
    k8singress:
      enabled: false
  policy:
    enabled: false
    image: "docker.io/istio/mixer:1.5.2"
    replicaCount: 1
    minReplicas: 1
    maxReplicas: 5
  telemetry:
    enabled: true
    image: "docker.io/istio/mixer:1.5.2"
    replicaCount: 1
    minReplicas: 1
    maxReplicas: 5
  sidecarInjector:
    enabled: false
    image: "docker.io/istio/sidecar_injector:1.5.2"
    replicaCount: 1
    rewriteAppHTTPProbe: true
    autoInjectionPolicyEnabled: true
    init:
      resources:
        requests:
          cpu: 10m
          memory: 10Mi
        limits:
          cpu: 100m
          memory: 50Mi
  nodeAgent:
    enabled: false
    image: "docker.io/istio/node-agent-k8s:1.5.2"
  proxy:
    image: "docker.io/istio/proxyv2:1.5.2"
    accessLogFile: "/dev/stdout"
    accessLogFormat: ""
    accessLogEncoding: "TEXT"
    enableCoreDump: false
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 2000m
        memory: 1024Mi
  proxyInit:
    image: "docker.io/istio/proxyv2:1.5.2"
  defaultPodDisruptionBudget:
    enabled: true
  outboundTrafficPolicy:
    mode: ALLOW_ANY
  tracing:
    enabled: true
    tracer: datadog
    zipkin:
      address: zipkin.istio-system:9411
    datadog:
        address: $(HOST_IP):8126
    lightstep:
        address: lightstep-satellite.lightstep:9292
        accessToken: <access-token>
        secure: true
        cacertPath: /etc/lightstep/cacert.pem
  localityLB:
    enabled: false
    # distribute:
    # - from: "us-central1/*"
    #   to:
    #     "us-central1/*": 80
    #     "us-central2/*": 20
    # failover:
    # - from: us-east
    #   to: eu-west
    # - from: us-west
    #   to: us-east
  jwtPolicy: "first-party-jwt"
```
