### ISSUE TITLE
Manage externalTrafficPolicy through operator

### ISSUE THREAD

**Issue by danil-fomichev** [banzaicloud/istio-operator#446]
**Is your feature request related to a problem? Please describe.**

Right ingress gateway service is deployed with externalTrafficPolicy=Cluster and there is no way to change it to 'Local' type in operator config. But externalTrafficPolicy=Local is the only way to retrieve real source IP from the access log.

**Describe the solution you'd like to see**

I would like to see the following option in the operator config:
```
  gateways:
    enabled: true
    ingress:
      enabled: true
      externalTrafficPolicy: Local
```

**Describe alternatives you've considered**

Right now the only way is to edit svc resource manually using kubectl.
