### ISSUE TITLE
Unable to attach annotations to gateway

### ISSUE THREAD

**Issue by mabushey** [banzaicloud/istio-operator#76]
**Describe the bug**
Unable to attach cert to ELB

Need to attach these annotations:
```
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-west-2:{act_num}:certificate/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "300"
```

The good news is the ELB already comes up as TCP. :) This is a huge improvement.

**Comment by martonsereg** [comment]
Thanks for reporting.
We’re working on getting on par with the Helm chart regarding configuration options, but just not there yet.
We’ll try to add this soon.

**Comment by matyix** [comment]
Hello @mabushey - thanks for reporting this, we have just added the feature and released [0.0.6](https://github.com/banzaicloud/istio-operator/releases/tag/0.0.6). `make deploy` should deploy the new version, please let us know how it works for you.

**Comment by jtimdwyer** [comment]
Hi @matyix, this is great and seems to work perfectly! For reference the following config brought up the desired load balancer with a certificate on the 443 listener as desired.

```
apiVersion: istio.banzaicloud.io/v1beta1
kind: Istio
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: istio
  namespace: istio-system
spec:
  mtls: false
  includeIPRanges: "*"
  excludeIPRanges: ""
  autoInjectionNamespaces:
  - "app-stg"
  - "app-prd"
  - "httpbin"
  controlPlaneSecurityEnabled: false
  gateways:
    ingress:
      serviceAnnotations:
        service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:{REGION}:{ACCT_NUMBER}:certificate/{CERT_UUID}"
        service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
        service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "300"
```
