### ISSUE TITLE
Istiod: metrics port is not usable

### ISSUE THREAD

**Issue by Obirah** [banzaicloud/istio-operator#810]
**Describe the bug**
The metrics port of istiod (15014) is not usable.

**Steps to reproduce the issue:**
Try to scrape the istiod, e.g:

```
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istio-component-monitor
  labels:
    monitoring: istio-components
spec:
  jobLabel: istio
  targetLabels: [app]
  selector:
    matchExpressions:
      - {key: istio, operator: In, values: [pilot]}
  namespaceSelector:
    any: true
  endpoints:
    - port: http-monitoring
       interval: 15s
```

The metrics will not show up in Prometheus.

On the other hand, if you port-forward port 15014 of istiod on your machine, you will be able to see the metrics at `localhost:15014/metrics`

**Expected behavior**
The metrics port should be accessible.

**Additional context**
Metrics port is configured [here](https://github.com/banzaicloud/istio-operator/blob/3cf51f7ea68dcc1aecfd7e0fb741a54c4530a230/pkg/resources/istiod/deployment.go#L49).

[Container ports](https://github.com/banzaicloud/istio-operator/blob/3cf51f7ea68dcc1aecfd7e0fb741a54c4530a230/pkg/resources/istiod/deployment.go#L203) do not contain the metrics port.

However, metrics port is contained in the [Service](https://github.com/banzaicloud/istio-operator/blob/3cf51f7ea68dcc1aecfd7e0fb741a54c4530a230/pkg/resources/istiod/service.go#L55).

I assume, simply adding the metrics port to the container ports will be sufficient to fix this.
