### ISSUE TITLE
IstioMeshGateway reconciliation does not honor spec.Deployment.Image value

### ISSUE THREAD

**Issue by Tanemahuta** [banzaicloud/istio-operator#818]
**Describe the bug**
When reconciling an `IstioMeshGateway` with `spec.deployment.image` set, the image is not used in the deployment.

**Steps to reproduce the issue:**
Create
```yaml
apiVersion: servicemesh.cisco.com/v1alpha1
kind: IstioMeshGateway
spec:
  deployment:
    image: my-repository.se/image-override:tag
```

**Expected behavior**
The deployment derived from the CR uses the image provided in the spec.

**Additional context**
Operator version: v2.11.6
