### ISSUE TITLE
the workload is not injected with sidecar,is that the namespace with istio-injection=enabled label,the workload will be injected

### ISSUE THREAD

**Issue by 13567436138** [banzaicloud/istio-operator#843]
**Describe the bug**
the workload is not injected with sidecar,is that the namespace with istio-injection=enabled label,the workload will be injected
**Steps to reproduce the issue:**
Please describe the steps to reproduce the issue.
I installed istio-operator,and istio,everything seems ok.but the workload did not injected with sidecar
**Expected behavior**
the workload injected sidecar
**Screenshots**

**Additional context**
Add any other context about the problem like release number version, branch, etc.

**Comment by Laci21** [comment]
Hi,

The `istio.io/rev=<YOUR_ICP_NAME>.istio-system` label should be used on the namespace and no `istio-injection=enabled`.

**Comment by dshmatov** [comment]
Hey @Laci21, got the same result when using the pod annotations for the granular sidecar injection. I've annotated pod with combinations of   `istio.io/rev: "istio-base.istio-system"` and `sidecar.istio.io/inject: "true"` but didn't get success. Have this webhook created:

```yaml
webhooks:
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    service:
      name: istiod-istio-base
      namespace: istio-system
      path: /inject
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: rev.namespace.sidecar-injector.istio.io
  namespaceSelector:
    matchExpressions:
    - key: istio.io/rev
      operator: In
      values:
      - istio-base.istio-system
    - key: istio-injection
      operator: DoesNotExist
  objectSelector:
    matchExpressions:
    - key: sidecar.istio.io/inject
      operator: NotIn
      values:
      - "false"
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    service:
      name: istiod-istio-base
      namespace: istio-system
      path: /inject
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: rev.object.sidecar-injector.istio.io
  namespaceSelector:
    matchExpressions:
    - key: istio.io/rev
      operator: DoesNotExist
    - key: istio-injection
      operator: DoesNotExist
  objectSelector:
    matchExpressions:
    - key: sidecar.istio.io/inject
      operator: NotIn
      values:
      - "false"
    - key: istio.io/rev
      operator: In
      values:
      - istio-base.istio-system
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10

```
