### ISSUE TITLE
Sidecar egress hosts are partially propagated

### ISSUE THREAD

**Issue by vitalii-buchyn-exa** [banzaicloud/istio-operator#929]
**Describe the bug**
Hello community,

We experience an issue when not all egress hosts from a Sidecar spec are propagated to envoy proxies.

Sidecar for example-svc:
```
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: example-svc
  namespace: myns
spec:
  egress:
  - hosts:  
    - istio-system/*
    - somens/*
    - core/core-svc.core.svc.cluster.local
  workloadSelector:
    labels:
      app: example-svc
```

DestinationRule for example-svc:
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: example-svc
  namespace: myns
spec:
  host: example-svc
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    outlierDetection:
      baseEjectionTime: 30s
      consecutive5xxErrors: 3
      interval: 10s
      maxEjectionPercent: 100
    tls:
      mode: ISTIO_MUTUAL
```

VirtualService for core-svc:
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: core-svc
  namespace: core
spec:
  gateways:
  - mesh
  hosts:
  - core-svc
  http:
  - retries:
      attempts: 5
      perTryTimeout: 60s
      retryOn: gateway-error,connect-failure,refused-stream
    route:
    - destination:
        host: core-svc
    timeout: 300s
```

Service for core-svc:
```
apiVersion: v1
kind: Service
metadata:
  name: core-svc
  namespace: core
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http-18080
    port: 80
    protocol: TCP
    targetPort: 18080
  selector:
    app: core-svc
  sessionAffinity: None
  type: ClusterIP
```

core-svc deployment is up and running.

There is no EnvoyFilter that may impact routes.
There is no ServiceEntry for core-svc.
There is no Sidecar duplicates for the same workload selector.

`istioctl pc cluster` and `istioctl pc route` show entries for istio-system and somens namespaces, but no entry for core-svc.
Debugging logs for istiod and istio-proxy do not show anything suspicious. istiod debug was turned on with `default:debug,all:debug`. istio-proxy debug was turned on with `istioctl proxy-config log POD --level=trace`.

istiod config_dump for example-svc doesn't have core-svc.

Meanwhile, for another application in the same cluster, in the same namespace, with a similar Sidecar configuration it works:
```
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: example2-svc
  namespace: cloud
spec:
  egress:
  - hosts:
    - istio-system/*
    - ./*
    - core/core-svc.core.svc.cluster.local
    - core/another-svc.core.svc.cluster.local
  workloadSelector:
    labels:
      app: example2-svc
```

What else we can check/debug/trace to see why the route has not been respected?

Any help would be appreciated.

Please let me know if any additional info is required.
Thanks!

**Expected behavior**
All hosts from Sidecar spec propagated.

**Additional context**
k8s version: v1.24.13-gke.2500
istio operator version: v2.16.1
istio-proxy version: istio-proxyv2:1.15.0
