### ISSUE TITLE
Routing with VirtualService not working as expected

### ISSUE THREAD

**Issue by jtimdwyer** [banzaicloud/istio-operator#96]
**Describe the bug**
Applying routing rules does not route as expected -- get a 404 on all routes.

In the code yaml files below I've replaced identifying information (hosts and various id numbers) with placeholders.

**Steps to reproduce the issue:**
Install the istio-operator by following the instructions i.e. running `make deploy`. Apply the following istio configuration.
```
apiVersion: istio.banzaicloud.io/v1beta1
kind: Istio
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: istio
  namespace: istio-system
spec:
  mtls: false
  includeIPRanges: "*"
  excludeIPRanges: ""
  autoInjectionNamespaces:
  - "app-stg"
  - "app-prd"
  - "httpbin"
  controlPlaneSecurityEnabled: false
  gateways:
    ingress:
      serviceAnnotations:
        service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:{REGION}:{ACCT_NUMBER}:certificate/{CERT_UUID}"
        service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
        service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "300"
```

Then create a virtual service as below 
```
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: app-stg
  namespace: default
spec:
  hosts:
  - "app-stg.example.com"
  - "app-stg.blue.example.com"
  - "app-stg.green.example.com"
  gateways:
  - istio-autogenerated-k8s-ingress
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 80
        host: httpbin.httpbin.svc.cluster.local
```

**Expected behavior**
The hosts listed above should be routed to httpbin (which is running in the namespace httpbin).

**Additional context**
Add any other context about the problem like release number version, branch, etc.
Using Istio operator 0.0.6.
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.6", GitCommit:"ab91afd7062d4240e95e51ac00a18bd58fddd365", GitTreeState:"clean", BuildDate:"2019-02-26T12:59:46Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.7", GitCommit:"65ecaf0671341311ce6aea0edab46ee69f65d59e", GitTreeState:"clean", BuildDate:"2019-01-24T19:22:45Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by waynz0r** [comment]
Hi @jtimdwyer,

thanks for checking out the operator!

The `istio-autogenerated-k8s-ingress` is there for backward compatibility and it is using `istio:ingress` selector as that setting was used in the 0.8 version.

I would suggest to create a new `gateway` with `istio: ingressgateway` selector for your services. Also the `gateway` and the `virtualservice` must be in the same namespace.

**Comment by waynz0r** [comment]
@jtimdwyer Looks like you can have the `virtualservice` and the `gateway` in different namespaces, but you have to use FQDN for the gateway name that case.

The following example should work just fine.

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: app-stg
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - "app-stg.example.com"
    - "app-stg.blue.example.com"
    - "app-stg.green.example.com"
    port:
      name: http
      number: 80
      protocol: HTTP2
```

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: app-stg
  namespace: default
spec:
  gateways:
  - app-stg.istio-system.svc.cluster.local
  hosts:
    - "app-stg.example.com"
    - "app-stg.blue.example.com"
    - "app-stg.green.example.com"
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: httpbin.httpbin.svc.cluster.local
        port:
          number: 80
```
